<!DOCTYPE html>
<html lang="en">
<head>
    <?php include __DIR__ . '/boilerplate_head.phtml'; ?>
</head>
<body>
<?php include __DIR__ . '/boilerplate_menu.phtml'; ?>
<div class="container-fluid">
    <div class="row">
        <?php include __DIR__ . '/boilerplate_side.phtml'; ?>
        <div class="col-sm-8">
            <?php if ($tablename == ''): ?>
                <h3>Add New Table</h3>
                <br>
                <form method="post" action="<?=$menu['add_table']?><?=$tablename?>" id="formAddTable">
                    <div class="form-group row">
                        <label for="tablename" class="col-sm-2 col-form-label">Table Name :</label>
                        <div class="col-sm-8">
                            <input type="text" name="tablename" id="tablename" class="form-control" pattern="^[a-zA-Z]{1}[a-zA-Z0-9_]*$" required>
                        </div>
                        <div class="col-sm-2">
                            <input type="hidden" name="tablefields" id="tablefields">
                            <input type="submit" name="create" value="Create Table">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Define Fields :</label>
                    </div>
                </form>
            <?php else: ?>
                <h3>Edit/Remove Table</h3>
                <br>
                <form method="delete" action="<?=$menu['remove_table']?><?=$tablename?>" id="formDeleteTable">
                    <div class="form-group row">
                        <label for="tablename" class="col-sm-2 col-form-label">Table Name :</label>
                        <div class="col-sm-8">
                            <input type="text" name="tablename" id="tablename" class="form-control" value="<?=$tablename?>" readonly>
                        </div>
                        <div class="col-sm-2">
                            <input type="submit" name="delete" value="Drop Table">
                        </div>
                    </div>
                    <div class="form-group row">
                        <label class="col-sm-2 col-form-label">Table Fields :</label>
                    </div>
                </form>
            <?php endif; ?>
            <table cellpadding="0" cellspacing="0" border="0" class="dataTable table table-striped" id="example">
            </table>
        </div>
    </div>
</div>
<?php include __DIR__ . '/boilerplate_body.phtml'; ?>
<script type="text/javascript">
    var fieldtypesOptions =
        { 
            "TEXT" : "TEXT", 
            "NUMERIC" : "NUMERIC", 
            "INTEGER" : "INTEGER",
            "REAL" : "REAL",
            "BLOB" : "BLOB"
        };
    $(document).ready(function() {
        let columnDefs = [
            { 
                data: "fieldname", 
                title: "Field Name",
                type: "text",
                pattern: "^[a-zA-Z]{1}[a-zA-Z0-9_]*$",
                required: true,
                unique: true 
            },
            { 
                data: "fieldtype", 
                title: "Field Type", 
                type : "select", 
                options: fieldtypesOptions
            }
        ];
        let oTable = $('#example').DataTable({
            "columns": columnDefs,
            "dom": 'Bfrtip',            // Needs button container
            "select": 'single',
            "responsive": true,
            "altEditor": true,          // Enable altEditor
            "buttons": [
                {
                    text: 'Add',
                    name: 'add'         // do not change name
                },
                {
                    extend: 'selected', // Bind to Selected row
                    text: 'Edit',
                    name: 'edit'        // do not change name
                },
                {
                    extend: 'selected', // Bind to Selected row
                    text: 'Delete',
                    name: 'delete'      // do not change name
                },
                {
                    text: 'Refresh',
                    name: 'refresh'     // do not change name
                }
            ],
            <?php if ($tablename == ''): ?>
            <?php else: ?>
            "ajax": {
                "url": "<?=$menu['list_schema']?>",
                "type": "GET"
            },
            <?php endif; ?>
            "sPaginationType": "full_numbers"
        });
        <?php if ($tablename == ''): ?>
        $('#formAddTable').submit(function(event) {
            var aData = JSON.stringify(oTable.data().toArray());
            console.log(aData);
            $('input[name=tablefields]').val(aData);
            // event.preventDefault();
        });
        <?php endif; ?>
    });
</script>
</body>
</html>