<nav class="navbar navbar-expand-lg navbar-light bg-light mb-3">
    <span class="navbar-brand mb-0 h1">Projapps<br>SQLite<br>Administrator</span>
    <button class="navbar-toggler" type="button"
            data-toggle="collapse" data-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            <li class="nav-item <?=$nav['home']?>"><a class="nav-link" href="<?=$menu['home']?>">Home</a></li>
            <li class="nav-item active"><span class="nav-link">|</span></li>
            <li class="nav-item <?=$nav['about']?>"><a class="nav-link" href="<?=$menu['about']?>">About</a></li>
            <li class="nav-item active"><span class="nav-link">|</span></li>
            <li class="nav-item"><a class="nav-link" href="https://github.com/nghianja/psa">GitHub</a></li>
            <li class="nav-item active"><span class="nav-link">|</span></li>
            <li class="nav-item"><a class="nav-link" id="login">Login</a></li>
        </ul>
    </div>
</nav>
<div class="modal fade" id="modalLogin" tabindex="-1" role="dialog">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <form id="formLogin" method="post" action="<?=$menu['login']?>">
            <div class="modal-header">
                <h5 class="modal-title">Login</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <?php if (!empty($errors) && array_key_exists('login', $errors[0])): ?>
                <div class="alert alert-danger" role="alert">
                    <?= $errors[0]['login'] ?>
                </div>
                <?php endif; ?>
                <div class="form-group">
                    <label for="username"></label>
                    <input type="text" name="username" id="username" placeholder="Username"
                           class="form-control <?=
                           (!empty($errors) && array_key_exists('username', $errors[0])) ? 'is-invalid' : '' ?>"
                           value="<?= empty($inputs) ? '' : $inputs[0]['username'] ?>" required>
                    <?php if (!empty($errors) && array_key_exists('username', $errors[0])): ?>
                    <p class="invalid-feedback">
                        <?php
                        $messages = $errors[0]['username'];
                        foreach ($messages as $message) {
                            echo $message . ". ";
                        }
                        ?>
                    </p>
                    <?php endif; ?>
                </div>
                <div class="form-group">
                    <label for="password"></label>
                    <input type="password" name="password" id="password" placeholder="Password"
                           class="form-control <?=
                           (!empty($errors) && array_key_exists('password', $errors[0])) ? 'is-invalid' : '' ?>"
                           value="<?= empty($inputs) ? '' : $inputs[0]['password'] ?>" required>
                    <?php if (!empty($errors) && array_key_exists('password', $errors[0])): ?>
                        <p class="invalid-feedback">
                            <?php
                            $messages = $errors[0]['password'];
                            foreach ($messages as $message) {
                                echo $message . ". ";
                            }
                            ?>
                        </p>
                    <?php endif; ?>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancel</button>
                <button type="submit" class="btn btn-primary" id="buttonLogin">Sign In</button>
            </div>
            </form>
        </div>
    </div>
</div>