<div id="menu">
    <a href="<?=$menu['home']?>">Home</a> |
    <a href="<?=$menu['about']?>">About</a> |
    <a href="https://github.com/nghianja/psa">GitHub</a> |
    <a id="login">Login</a>
    <form id="formLogin" class="forms">
        <label for="username"></label>
        <input type="text" name="username" id="username">
        <br>
        <label for="password"></label>
        <input type="password" name="password" id="password">
        <br>
        <input type="submit" name="mysubmit" value="Login">
        <input type="reset" name="myreset" value="Cancel">
    </form>
    <ul id="error">
    </ul>
</div>