<meta charset="utf-8"/>
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<title>Projapps SQLite Administrator</title>
<style type="text/css" media="screen">
    @import "https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css";
    @import "https://cdn.datatables.net/1.10.19/css/jquery.dataTables.min.css";
    @import "styles/main.css";
</style>