<div class="col-sm-2">
    <form>
        <fieldset class="border p-2">
            <legend class="w-auto">Database</legend>
            <p>Version <?=$version?></p>
        </fieldset>
        <br>
        <fieldset class="border p-2">
            <legend class="w-auto">Tables</legend>
            <p>
                <?php
                foreach ($tables as $table) {
                    echo $table;
                    echo '<br>';
                }
                ?>
            </p>
        </fieldset>
        <br>
        <?php
        if ($username == 'admin') {
            echo '<fieldset class="border p-2">';
            echo '<legend class="w-auto">Admin</legend>';
            echo '<p>';
            foreach ($tables as $table) {
                echo '<a href="/admin/edit/' . $table . '">' . $table . '</a>';
                echo '<br>';
            }
            echo '<a href="' . $menu['add_admin'] . '">add_new_table</a>';
            echo '</p>';
            echo '</fieldset>';
        }
        ?>
    </form>
</div>