<script type="text/javascript" src="https://code.jquery.com/jquery-3.3.1.js"></script>
<script type="text/javascript" src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script type="text/javascript" src="scripts/dataTables.altEditor.free.min.js"></script>
<script type="text/javascript">
    var username = "<?=$username?>";
</script>
<script type="text/javascript" src="scripts/main.js"></script>