<!DOCTYPE html>
<html lang="en">
<head>
    <?php include __DIR__ . '/boilerplate_head.phtml'; ?>
</head>
<body>
<?php include __DIR__ . '/boilerplate_menu.phtml'; ?>
<div class="container-fluid">
    <div class="row">
        <?php include __DIR__ . '/boilerplate_side.phtml'; ?>
        <div class="col-sm-8">
            <table cellpadding="0" cellspacing="0" border="0" class="dataTable table table-striped" id="example">
            </table>
        </div>
    </div>
</div>
<?php include __DIR__ . '/boilerplate_body.phtml'; ?>
<script type="text/javascript">
    $(document).ready(function() {
        let columnDefs = [
            <?php
            foreach ($fields as $field) {
                if ($field['name'] == "id") echo '{ readonly: true, ';
                else echo ",\r\n            { ";
                echo 'data: "' . $field['name'] . '", ';
                echo 'title: "' . $field['name'] . '" }';
            }
            echo "\r\n";
            ?>
        ];
        let oTable = $('#example').DataTable({
            "columns": columnDefs,
            "dom": 'Bfrtip',            // Needs button container
            "select": 'single',
            "responsive": true,
            "altEditor": true,          // Enable altEditor
            "buttons": [
                {
                    text: 'Add',
                    name: 'add'         // do not change name
                },
                {
                    extend: 'selected', // Bind to Selected row
                    text: 'Edit',
                    name: 'edit'        // do not change name
                },
                {
                    extend: 'selected', // Bind to Selected row
                    text: 'Delete',
                    name: 'delete'      // do not change name
                },
                {
                    text: 'Refresh',
                    name: 'refresh'     // do not change name
                }
            ],
            "sPaginationType": "full_numbers",
            "ajax": {
                "url": "<?=$menu['list_data']?>",
                "type": "GET"
            },
            "onAddRow": function(datatable, rowdata, success, error) {
                console.log(rowdata);
                $.ajax({
                    "url": "<?=$menu['add_data']?>",
                    "type": "POST",
                    contentType: "application/json",
                    data: JSON.stringify(rowdata),
                    success: success,
                    error: error
                });
            },
            "onEditRow": function(datatable, rowdata, success, error) {
                $.ajax({
                    "url": "<?=$menu['edit_data']?>",
                    "type": "PUT",
                    data: rowdata,
                    success: success,
                    error: error
                });
            },
            "onDeleteRow": function(datatable, rowdata, success, error) {
                $.ajax({
                    "url": "<?=$menu['delete_data']?>",
                    "type": "DELETE",
                    data: rowdata,
                    success: success,
                    error: error
                });
            }
        });
    });
</script>
</body>
</html>