<!DOCTYPE html>
<html lang="en">
<head>
    <?php include __DIR__ . '/boilerplate_head.phtml'; ?>
</head>
<body>
<div id="acronym">P.S.A.</div>
<?php include __DIR__ . '/boilerplate_menu.phtml'; ?>
<div id="spacing">Projapps SQLite Administrator</div>
<?php include __DIR__ . '/boilerplate_side.phtml'; ?>
<div id="main">
    <!-- form method="post" action="list_data/<?=$tablename?>" id="formAddNewRow" title="Add New Row">
        <?php
        $counter = 0;
        foreach ($fields as $field) {
            if ($field['name'] == 'id') {
                echo '<input type="hidden" name="' . $field['name'] . '" value="DATAROWID" rel="' . $counter . '" />';
            } else {
                echo '<label for="' . $field['name'] . '">' . $field['name'] . '</label>';
                echo '<br>';
                echo '<input type="text" name="' . $field['name'] . '" id="' . $field['name'] . '" class="required" rel="' . $counter . '" />';
                echo '<br>';
            }
            $counter++;
        }
        ?>
    </form -->
    <table cellpadding="0" cellspacing="0" border="0" class="display" id="example">
        <thead>
        <tr>
            <?php
            $counter = 0;
            foreach ($fields as $field) {
                echo '<th>' . $field['name'] . '</th>';
                $counter++;
            }
            ?>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>
<?php include __DIR__ . '/boilerplate_body.phtml'; ?>
<script type="text/javascript">
    $(document).ready(function(){
        var oTable = $('#example').DataTable({
            "bFilter": false,
            "bSort": false,
            "bJQueryUI": false,
            "bProcessing": true,
            "bServerSide": true,
            "sPaginationType": "full_numbers",
            "sAjaxSource": "<?=$menu['list_data']?>",
            "fnServerData": function (sSource, aoData, fnCallback){
                $.ajax({
                    "dataType": 'json',
                    "type": "POST",
                    "url": sSource,
                    "data": aoData,
                    "success": fnCallback
                });
            },
            "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull){
                nRow.id = aData[0];
                return nRow;
            }
        });
        /*
        oTable.makeEditable({
            sUpdateURL: "<!-- ?php echo 'edit_data/' . $tablename ? -->",
            sAddURL: "<!-- ?php echo 'add_data/' . $tablename ? -->",
            sDeleteURL: "<!-- ?php echo 'remove_data/' . $tablename ? -->",
            sAddDeleteToolbarSelector: ".dataTables_length"
        });
        */
    });
</script>
</body>
</html>